server:
    port: 8082
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        input-transfer:
          destination: greetings
          contentType: application/json
        output-transfer:
          destination: greetings
          contentType: application/json